-- TRUNCATE TABLE APP.SCULPTURES;
INSERT INTO APP.SCULPTURES (TITLE, DESCRIPTION, CATEGORY, SIZE_IN_CM, INSURANCE_PRICE) VALUES

  ('Ail des ours', 'Terre cuite patinée et poinçon','Plante', 22, 360),
  ('Akène de pissenlit x 8', 'Terre cuite, parasol chinois et roseau','Mobiles', NULL, NULL),
  ('Akène de pissenlit x 9', 'Terre cuite, parasol chinois et roseau','Mobiles', 16, 60),
  ('Aneth', 'Terre cuite patinée','Plantes', 45, 310),
  ('Arachide', 'Terre cuite patinée et fibres','Plantes', 50, 520),
  ('Araucaria', 'Cazette','Arbre', 22, 390),
  ('Arbouse', 'Terre vernissée','Arbre', 40, 580),
  ('Baobab', 'Terre cuite patinée','Arbre', 25, 420),
  ('Blé', 'Terre cuite et billet de banque','plante', NULL, 520),
  ('Bourrache', 'Terre cuite patinée','Plantes', NULL, 380),
  ('Bractées de tilleul x 8', 'Terre cuite, laiton, carton, papier simple','Mobiles', 50, 120),
  ('Bractées de tilleul x 8', 'Terre cuite, laiton, carton, papier simple','Mobiles', NULL, 80),
  ('Bractées de tilleul x 8', 'triple','Mobiles', 100, 120),
  ('Buis', 'Terre cuite patinée et émaillée','Arbuste', 45, NULL),
  ('Bulbe de fenouil', 'Terre cuite patinée','Plantes', NULL, 420),
  ('Cacao', 'Terre cuite patinée','Arbre', 25, 380),
  ('Café', 'Terre cuite patinée','Arbre', 50, 550),
  ('Campanule', 'Engobe vitrifié et pièce métallique','Plante', 40, 450),
  ('Capsule de camelia', 'Terre cuite patinée','Arbre', 35, 450),
  ('Capsule de lin', 'Terre cuite patinée','Plantes', NULL, 480),
  ('Cardamome', 'Terre cuite patinée et gravure ancienne','plante', 30, 425),
  ('Cardiospermum', 'terre cuite émaillée','plante', 25, 460),
  ('Chanvre', 'Terre cuite patinée','Plantes', NULL, 240),
  ('Charme', 'Terre cuite, engobe vitrifié','Arbre', 50, 380),
  ('Châtaigne', 'Terre cuite patinée','Arbre', 40, 340),
  ('Châtaigne', 'Terre cuite patinée','Arbre', 35, 350),
  ('Châtaigne d''eau', 'Terre cuite patinée','Plantes', 40, 460),
  ('Cosse de lilas', 'Terre cuite raku','Arbre', NULL, 450),
  ('Cosse de luzerne', 'Terre cuite patinée','Germination', 35, 320),
  ('Courge accorn', 'Terre cuite patinée et composants électroniques','plante', 13, 180),
  ('Dahlia', 'Terre cuite teintée et papier','Plantes', 45, 230),
  ('Delonix flamboyant', 'Terre cuite patinée','Arbre', 50, 380),
  ('Delphinium', 'Terre cuite enfumée','Plantes', NULL, 600),
  ('Eglantine', 'Terre cuite patinée','Arbre', NULL, 450),
  ('Entada giga', 'Grès','Plante', 50, 500),
  ('Eucalyptus new', 'Terre cuite patinée','Arbre', 25, NULL),
  ('Euphorbe', 'Terre cuite patinée et partition musicale','Plante', NULL, 532),
  ('Exochorda', 'Terre cuite patinée','Arbre', 18, 428),
  ('Faîne de hêtre', 'Terre cuite patinée','Arbre', 50, 420),
  ('Fève', 'Terre cuite patinée','Plantes', NULL, 320),
  ('Févier d''Amérique', 'Engobe vitrifié','Arbre', 45, NULL),
  ('Frêne x 10', 'Terre cuite patinée','Mobiles', 30, 220),
  ('Garance', 'Terre cuite enfumée et patinée','Plantes', NULL, 320),
  ('Girofle', 'Terre cuite patinée','Arbre', 50, 290),
  ('Gland', 'Terre cuite enfumée et patinée','Arbre', 50, 580),
  ('Gland', 'Raku nu','Arbre', NULL, 420),
  ('Glycine', 'Terre cuite patinée et filtre 3D','Plantes', NULL, 320),
  ('Graines d’hibiscus x 5', 'Terre cuite patinée et fourrure','Mobiles', 15, 60),
  ('Grandes samares x 5', 'Terre cuite patinée','Mobiles', 60, 95),
  ('Gyroflee', 'Terre cuite patinée et vilebrequin','Mobiles', 50, 420),
  ('haricoreille', 'Grès','Plantes', 15, 95),
  ('Haricot germant', 'Terre cuite patinée','Germination', 30, NULL),
  ('Haricot Mungo', 'Terre cuite patinée','Germination', 40, 440),
  ('Heritiera', 'raku','Arbre', 40, 350),
  ('Hevea', 'Terre cuite en cazette','arbre', 28, 560),
  ('Hortensia', 'Terre cuite raku et outil ancien','Plantes', 30, 410),
  ('Iris', 'Terre cuite patinée','Plante', 40, 380),
  ('Jacaranda', 'Terres cuites patinées','Arbre', 38, 480),
  ('Juglans nigra', 'grès, porcelaine et pain','Arbre', 23, 320),
  ('Lagerstroemia', 'Terre cuite patinée et porte outil','Arbre', 25, 420),
  ('Lentille germant', 'Terre cuite patinée et filtre UV','Germination', NULL, 320),
  ('Lessiveuse', 'Terre cuite et pièce en cuivre','Plantes', 30, 280),
  ('Lentille germée', 'Terre cuite patinée','Plantes', 28, NULL),
  ('Lotus', 'Terre cuite patinée','Plantes', 30, 390),
  ('Lunaire silique', 'Vitrail et terre cuite','Mobiles', NULL, 510),
  ('Lychnis', 'Terre cuite patinée','Plantes', NULL, 620),
  ('Maïs', 'Terre cuite émaillée','Plantes', NULL, 210),
  ('Mandarine séchée', 'Terre cuite patinée','Plantes', 23, 380),
  ('Marron d''Inde', 'raku nu','Arbre', 40, 530),
  ('Marron d''Inde', 'Grès','Arbre', 40, 530),
  ('Marron d''Inde', 'Terre cuite sigillée','Arbre', 25, 420),
  ('Muflier', 'Terre cuite enfumée et transert','Plantes', 32, 630),
  ('Nicandra', 'Tere cuite, cuisson en cazette','Plantes', 35, 620),
  ('Nigelle', 'Raku','Plantes', 45, 520),
  ('Noisette', 'raku nu','Arbre', NULL, 530),
  ('Noix', 'Terre cuite patinée','Arbre', NULL, 380),
  ('Noyau de pêche', 'Terre cuite patinée aux épices','Arbre', NULL, 310),
  ('Oignon', 'Grès et papier verni','Plantes', NULL, 380),
  ('Olive', 'Terre cuite engobée et vernissée','Arbre', 40, 320),
  ('Onagre', 'terre cuite et cire d''abeille','Plante', 40, 480),
  ('Onobrychis', 'Terre cuite patinée','Plante', 35, 350),
  ('Orme x 8', 'Terre cuite patinée et papier','Mobiles', 14, 40),
  ('Paliure', 'Terre cuite patinée','Arbre', 40, NULL),
  ('Pastel', 'Terre cuite , pastel','Plantes', 50, 520),
  ('Pastel germant', 'Terre cuite patinée toile teinte, bois, métal','Plantes', 50, NULL),
  ('Patate germée', 'Terre cuite engobée','Plantes', 40, 320),
  ('Pavot', 'Raku','Plantes', 40, 460),
  ('Pavot OGM', 'Terre cuite, foret, roulement à bille','Plantes', 45, 420),
  ('Pavot tuyau', 'Cuisson en cazette , embout de tuyau en laiton','Plantes', 35, 480),
  ('Pavot tuyau Grand', 'Engobe vitrifié, embout en cuivre','Plantes', 45, 620),
  ('Physalis Franchetti', 'Terre cuite patinée','Plantes', 30, 320),
  ('Pigne Salzman', 'Terre cuite patinée','Arbre', 50, NULL),
  ('Pignons de pin x 6', 'Terre cuite patinée et papier','Mobiles', 30, 60),
  ('Poire séchée', 'Terre cuite patinée','Arbre', NULL, 540),
  ('Pois chiche germant', 'Terre cuite patinée','Germination', 20, NULL),
  ('Pterocaria', 'grès, cuisson au bois','Arbre', 25, 310),
  ('Ptiteuca', 'Cazette','Arbre', 18, NULL),
  ('Quinoa germant', 'Terre cuite patinée','Germination', 20, 340),
  ('Rhododendron', 'Terre cuite et outil','Arbre', 50, 460),
  ('Rosier', 'Terre cuite en cazette et patinée','Plantes', 25, 520),
  ('Rue Officinale', 'Terre cuite et outil','Plantes', 40, 450),
  ('Rumex crispus', 'porcelaine','Plantes', 28, 310),
  ('Samares d’érable x 5', 'Terre cuite et lettres anciennes','Mobiles', 25, 90),
  ('Samares d’érable x 5', 'Terre cuite et lettres anciennes','Mobiles', NULL, 110),
  ('Samares d’érable x 3', 'Terre cuite patinée','Mobiles', 60, 120),
  ('Sauge', 'Terre cuite en cazette','plante', 28, 480),
  ('Saule', 'Terre cuite patinée, émail, coton','Arbre', NULL, 550),
  ('Schreberra', 'Terre cuite patinée et vieux sécateur','Arbre', 25, 480),
  ('Scrofulaire', 'Terre cuite et outil','Plantes', 20, 230),
  ('Souci', 'Grès et papier','Plantes', NULL, 360),
  ('Tabac', 'terre enfumée et patinée','Plante', 40, 480),
  ('Tetraclinis 2', 'raku','Arbre', 20, 320),
  ('Tetraptera tetrapleura', 'Terre cuite patinée','Arbre', 60, 540),
  ('Thespesia', 'Terre cuite et papier','Arbre', 28, 480),
  ('Tomate', 'Terre cuite patinée','Plantes', 40, 420),
  ('Tournesol', 'Terre cuite patinée','Plante', NULL, 560),
  ('Tranche de pomme séchée', 'Terre cuite patinée','Arbre', NULL, 210)

;
